### ISSUE TITLE
bad option --allow-superuser in ci

### ISSUE THREAD

**Issue by sakulstra** [EducationLink/meteor-google-cloud#21]
Currently trying to update an app from 1.8.1 to 1.10.1 and are getting the error reported at the meteor repository
https://github.com/meteor/meteor/issues/10894#issuecomment-581227188 

```
error:   exec: /builder/home/.meteor/packages/meteor-tool/.1.9.0.1mtsmz6.qnno++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: bad option: --allow-superuser
```

Any idea what the problem could be?

I cannot reproduce it locally.

**Comment by iamstevendao** [comment]
The workaround is to pass `--node-version` and `--npm-version` in `v1.2.0` until we know why `bad-option` error throws from meteor >= 1.9
