### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by raphaelarias** [EducationLink/meteor-google-cloud#7]

**Comment by HazemKhaled** [comment]
I'm using Buddy.works, and getting errors cos of my service account permissions .. it's ok i'm working on, but the result is pass while expect to have failed, maybe because of the npm don't throw an error if the process failed

```
ERROR: (gcloud.app.deploy) User [buddy-dev@knawat-supply-dev.iam.gserviceaccount.com] does not have permission to access project [knawat-supply-dev] (or it may not exist): The caller does not have permission
Build finished successfully!.
```
